### ISSUE TITLE
Google colab and CUDA 12.2

### ISSUE THREAD

**Issue by Ash100** [RyanZR/ColabDock-Vina#7]
Hello Ryan,
Thanks for writing such great notebooks for the community. Google colab is shifted to CUDA 12.2. As a result, the mamba installation script are not getting success. 
`!mamba install -c conda-forge -c bioconda mgltools=1.5.7 biopython=1.80 openbabel=3.1.1 plip=2.2.2 zlib=1.2.13 xlsxwriter=3.0.3`

The installation log generates,

> No package can be installed for pin: cudatoolkit 12.2.*

I tried different things, like mentioning cudatoolkit=12.2 in the script, also remove the package version details, so that conda installs the appropriate version by itself. Nothing is working.
Will you be able to update the code?
Thanks

**Comment by RyanZR** [comment]
Hi @Ash100, I will be looking into it soon. 
Thank you for the heads up.

**Comment by RyanZR** [comment]
This issue is reported in [issue #60](https://github.com/conda-incubator/condacolab/issues/60). The presence of `CUDA v12.2` causes condacolab to inject a pin of `cudatoolkit 12.2.*`. Since Conda Forge isn't yet building `cudatoolkit=12.2`, this breaks Mamba for now. 

Two quick temporary workarounds would be:
**1. Remove the pinned file from Conda-Meta**
```python
!pip install condacolab==0.1.7
import condacolab
condacolab.install_mambaforge()
!rm -rf /usr/local/conda-meta/pinned # ADD THIS LINE HERE
!mamba env update --file environment.yml
``` 
**2. Install archived CondaColab with CUDA 12.x support**
```python
!pip install -U https://github.com/conda-incubator/condacolab/archive/cuda-version-12.tar.gz # REPLACE WITH THIS LINE
import condacolab
condacolab.install_mambaforge()
!mamba env update --file environment.yml
```
Until [PR #63](https://github.com/conda-incubator/condacolab/pull/63) gets merged in, applying either one of the workaround should fix the issue for now. Let me know if this solve the problem.

**Comment by RyanZR** [comment]
Hi @Ash100, [PR #63](https://github.com/conda-incubator/condacolab/pull/63) has been merged. The installation process should be working fine again. 
Please try the notebooks at the [develop branch](https://github.com/RyanZR/labodock/tree/develop).
